// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSJ8m4GIqT5X8G3g2d0YpelIZ-vha67o',
    appId: '1:1013253882056:web:5322ae8808909f627da5fd',
    messagingSenderId: '1013253882056',
    projectId: 'evently-7c3e0',
    authDomain: 'evently-7c3e0.firebaseapp.com',
    storageBucket: 'evently-7c3e0.firebasestorage.app',
    measurementId: 'G-M8CXZN0VMC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASV7wIhXyk-UfHdTsjsa7ZZL6AoQMHzJk',
    appId: '1:1013253882056:android:dc7a47bebf3cbc6e7da5fd',
    messagingSenderId: '1013253882056',
    projectId: 'evently-7c3e0',
    storageBucket: 'evently-7c3e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK_LwR1zuHR3hkTYkXR4OpJQWwwJnffZc',
    appId: '1:1013253882056:ios:6e120649ae1f5ad97da5fd',
    messagingSenderId: '1013253882056',
    projectId: 'evently-7c3e0',
    storageBucket: 'evently-7c3e0.firebasestorage.app',
    iosBundleId: 'com.example.eventlyV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK_LwR1zuHR3hkTYkXR4OpJQWwwJnffZc',
    appId: '1:1013253882056:ios:6e120649ae1f5ad97da5fd',
    messagingSenderId: '1013253882056',
    projectId: 'evently-7c3e0',
    storageBucket: 'evently-7c3e0.firebasestorage.app',
    iosBundleId: 'com.example.eventlyV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChSJ8m4GIqT5X8G3g2d0YpelIZ-vha67o',
    appId: '1:1013253882056:web:fb3b727fcfdb6e9f7da5fd',
    messagingSenderId: '1013253882056',
    projectId: 'evently-7c3e0',
    authDomain: 'evently-7c3e0.firebaseapp.com',
    storageBucket: 'evently-7c3e0.firebasestorage.app',
    measurementId: 'G-4YYWFSG9N8',
  );
}
